version: "3.1"
services:
  php:
    container_name: bd_php
    #image: php:fpm-alpine
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db
    networks:
      - default
  db:
    image: mysql:8.0
    container_name: bd_mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: daw
      MYSQL_USER: a22pedrovsp
      MYSQL_PASSWORD: 3892
      MYSQL_ROOT_PASSWORD: 3892
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./db/conf:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    container_name: bd_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
#      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_USER: a22pedrovsp
      MYSQL_PASSWORD: 3892
      MYSQL_ROOT_PASSWORD: 3892
    depends_on:
      - db
    networks:
      - default
volumes:
  persistent:
